import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./providers";
import { fonts } from "./fonts";
import { register } from "swiper/element/bundle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

register();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.worksans.variable}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
